MCU			= atmega32u4
BOOTLOADER		= atmel-dfu

SPLIT_KEYBOARD		= yes
MOUSEKEY_ENABLE		= yes
EXTRAKEY_ENABLE		= yes
NKRO_ENABLE		= yes
COMBO_ENABLE		= yes
UNICODEMAP_ENABLE	= yes

DEFAULT_FOLDER		= 3D_Keyboard/rev1
