MCU			= atmega32u4
BOOTLOADER		= atmel-dfu

SPLIT_KEYBOARD		= yes
STENO_ENABLE		= yes
MOUSEKEY_ENABLE		= no
EXTRAKEY_ENABLE		= no
NKRO_ENABLE		= yes
COMBO_ENABLE		= yes

DEFAULT_FOLDER		= 3D_Keyboard/rev1
